app/Models/QuizModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace app.Models
{
    public class QuizModel
    {
        public readonly List<string> AvailableOperations = new List<string>(new string[] { "+", "-", "*" });
        public double Number1 { get; set; }
        public double Number2 { get; set; }
        public string Operation { get; set; }
        public double Solution { get; set; }
        [Range(-100, 100)]
        [Required]
        public int UserAnswer { get; set; }

        public string Answer { get; set; }
        public List<string> AllAnswers;
        public int Count;
        public int CountOfRightAnswers;
        public static QuizModel Instance { get; set; } = new QuizModel(1);
        public QuizModel()
        {

        }
        private QuizModel(int i)
        {

        }
        public void Reset()
        {
            Count = 0;
            CountOfRightAnswers = 0;
            AllAnswers = new List<string>();
        }

        public void Start()
        {
            Random rand = new Random();
            Number1 = rand.Next(0, 10);
            Number2 = rand.Next(1, 10);
            Operation = rand.Next(3) switch
            {
                0 => "+",
                1 => "-",
                2 => "*",
                _ => throw new Exception("Unable to match proper operation")
            };
            Count++;

        }




        public void Questions()
        {
            switch (Operation)
            {
                case "+":
                    Solution = Number1 + Number2;
                    if (Solution == UserAnswer)
                        CountOfRightAnswers++;

                    AllAnswers.Add(Number1 + " + " + Number2 + " = " + UserAnswer);
                    break;
                case "-":
                    Solution = Number1 - Number2;
                    if (Solution == UserAnswer)
                        CountOfRightAnswers++;

                    AllAnswers.Add(Number1 + " - " + Number2 + " = " + UserAnswer);
                    break;
                case "*":
                    Solution = Number1 * Number2;
                    if (Solution == UserAnswer)
                        CountOfRightAnswers++;

                    AllAnswers.Add(Number1 + " * " + Number2 + " = " + UserAnswer);
                    break;
                default:
                    throw new Exception("Unable to handle operation");
            }
        }

        public class QuizOperationAttribute : ValidationAttribute
        {

            string[] _names;

            public QuizOperationAttribute(string[] names)
            {
                _names = names;
            }
            public override bool IsValid(object value)
            {
                if (value != null && _names.Contains(value.ToString()))
                    return true;

                return false;
            }
        }

    }
}

app/Controllers/QuizServiceController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using app.Models;

namespace app.Controllers
{
    public class QuizServiceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public IActionResult Quiz()
        {
            QuizModel qModel = QuizModel.Instance;
            qModel.Reset();
            qModel.Start();


            return View(qModel);
        }

        [HttpPost]
        public IActionResult Quiz(QuizModel qModel, string action)
        {
            qModel = QuizModel.Instance;

            if (ModelState.IsValid)

            {
                if (Request.Form["Answer"] != "") qModel.UserAnswer = Int32.Parse(Request.Form["Answer"]);
                else qModel.UserAnswer = 0;
                qModel.Questions();



                if (action == "Next")
                {
                    QuizModel quModel = QuizModel.Instance;
                    quModel.Start();

                    return View(quModel);
                }
                return RedirectToAction("QuizResult");
            }
            else
            {

                QuizModel quModel = QuizModel.Instance;
                return View(quModel);
            }

        }
        public IActionResult QuizResult()
        {
            QuizModel qModel = QuizModel.Instance;
            ViewBag.Result = qModel.AllAnswers;
            ViewData["Всего"] = "" + qModel.Count;
            ViewData["Правильно"] = "" + qModel.CountOfRightAnswers;
            return View();
        }



    }
}

app/Views/QuizService/Index.cshtml
@{
    ViewBag.Title = "Home Page - Backend1";
}
<h1>Mockups</h1>
<ul>
    <li><a asp-controller="QuizService" asp-action="Quiz">Quiz</a></li>
    <li><a asp-controller="QuizService" asp-action="QuizResult">QuizResult</a></li>
</ul>

app/Views/QuizService/Quiz.cshtml
@model app.Models.QuizModel
@{ ViewBag.Title = "Quiz"; }
<h2>Quiz</h2>
<b>@Model.Number1  @Model.Operation @Model.Number2 =</b>
<br />
<form asp-controller="QuizService">
    <input name="Answer" class="mb-3 mr-3" /><br />
    <div class="mb-3">
        <input type="submit" value="Next" name="action" class="btn btn-outline-secondary btn-sm" />
        <input type="submit" value="Finish" name="action" class="btn btn-primary btn-sm" />
    </div>
</form>

app/Views/QuizService/QuizResult.cshtml
@{ ViewBag.Title = "Quiz"; }
<h2>Quiz results</h2>
<h4>Right answers @ViewData["Правильно"] out @ViewData["Всего"]</h4>
<ol>
    @if (ViewBag.Result != null)
    {
        @foreach (var p in (ViewBag.Result))
        {
            <li>@p</li>
        }
    }
    else
            {
                <li>No available results</li>
            }
</ol>

app/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<header>
    <h2>Backend1</h2>
    <nav><a asp-controller="QuizService" asp-action="Index">Home</a></nav>
</header>
<main>
    @RenderBody()
</main>
<footer>
    <hr/>
    © 2021 - backend
</footer>
</body>
</html>